Django_dailyfresh_project/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include(("tinymce.urls", "tinymce"))),
    path("search/", include(("haystack.urls", "haystack"))),
    path("user/", include(("user.urls", "user"), namespace="user")),
    path("cart/", include(("cart.urls", "cart"), namespace="cart")),
    path("order/", include(("order.urls", "order"), namespace="order")),
    path("", include(("goods.urls", "goods"), namespace="goods")), 
]

apps/cart/urls.py
from django.urls import path
from cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

urlpatterns = [
    path("add", CartAddView.as_view(), name="add"),
    path("", CartInfoView.as_view(), name="show"),
    path("update", CartUpdateView.as_view(), name="update"),
    path("delete", CartDeleteView.as_view(), name="delete"),  
]

apps/goods/urls.py
from django.urls import path
from goods.views import IndexView, DetailView, ListView

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("index/", IndexView.as_view(), name="index"),
    path("goods/<int:goods_id>", DetailView.as_view(), name="detail"),
    path("list/<int:type_id>/<int:page>", ListView.as_view(), name="list"), 
]

apps/order/urls.py
from django.urls import path
from order.views import OrderPlaceView, OrderCommitView, OrderPayView, CheckPayView,CommentView

urlpatterns = [
    path("place", OrderPlaceView.as_view(), name="place"),
    path("commit", OrderCommitView.as_view(), name="commit"),
    path("pay", OrderPayView.as_view(), name="pay"),
    path("check", CheckPayView.as_view(), name="check"),
    path("comment/<int:order_id>", CommentView.as_view(), name="comment"),
]

apps/user/urls.py
from django.urls import path, re_path
from user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, AddressView

urlpatterns = [
    path("register", RegisterView.as_view(), name="register"),
    re_path("active/(?P<token>.*)$", ActiveView.as_view(), name="active"),
    path("login", LoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("", UserInfoView.as_view(), name="user"),
    path("order/<int:page>", UserOrderView.as_view(), name="order"),
    path("address", AddressView.as_view(), name="address"), 
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin


# CartAddView, CartInfoView, CartUpdateView, CartDeleteView

class CartAddView(View):
    
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({"res": 0, "errmsg": "Please login"})

        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        if not all([sku_id, count]):
            return JsonResponse({"res": 1, "errmsg": "Incomplete data"})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({"res": 2, "errmsg": "Wrong product numbers"})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"res": 3, "errmsg": "The product doesn't exist"})

        conn = get_redis_connection("default")
        cart_key = "cart_%s" % user.id
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            count += int(cart_count)

        if count > sku.stock:
            return JsonResponse({"res": 4, "errmsg": "Out of stock"})

        conn.hset(cart_key, sku_id, count)

        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({"res": 5, "total_count": total_count, "message": "Successfully added"})


class CartInfoView(LoginRequiredMixin, View):
    
    def get(self, request):
        user = request.user
        conn = get_redis_connection("default")
        cart_key = "cart_%d" % user.id
        cart_dict = conn.hgetall(cart_key)
        skus = []
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():

            sku_id = sku_id.decode()
            count = count.decode()

            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price * int(count)
            sku.amount = amount
            sku.count = count
            skus.append(sku)

            total_count += int(count)
            total_price += amount

        context = {"total_count": total_count, "total_price": total_price, "skus": skus}

        return render(request, "cart.html", context)


class CartUpdateView(View):
    
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({"res": 0, "errmsg": "Please login"})

        sku_id = request.POST.get("sku_id")
        count = request.POST.get("count")

        if not all([sku_id, count]):
            return JsonResponse({"res": 1, "errmsg": "Incomplete data"})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({"res": 2, "errmsg": "Wrong product numbers"})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"res": 3, "errmsg": "The product doesn't exist"})

        conn = get_redis_connection("default")
        cart_key = "cart_%d" % user.id

        if count > sku.stock:
            return JsonResponse({"res": 4, "errmsg": "Out of stock"})

        conn.hset(cart_key, sku_id, count)
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        return JsonResponse({"res": 5, 'total_count':total_count, "message": "Update successfully"})


class CartDeleteView(View):
    
    def post(self, request):

        user = request.user
        if not user.is_authenticated:
            return JsonResponse({"res": 0, "errmsg": "Please login"})

        sku_id = request.POST.get("sku_id")

        if not sku_id:
            return JsonResponse({"res": 1, "errmsg": "Invalid product id"})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({"res": 2, "errmsg": "The product doesn't exist"})

        conn = get_redis_connection("default")
        cart_key = "cart_%d" % user.id

        conn.hdel(cart_key, sku_id)

        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({"res": 3, "total_count": total_count, "message": "Delete successfully"})

templates/base.html
{# Home page register login #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# Title #}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# topfiles #}
    {% block topfiles %}{% endblock %}
</head>
<body>
{# Welcome info #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">Welcome to Dailyfresh!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        Hello, <em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">Sign Out</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">Login</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">Register</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">User Center</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">Cart</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">Orders</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{# 网页顶部搜索块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo02.png' %}"></a>
        <div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="Search...">
                <input type="submit" class="input_btn fr" name="" value="Search">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">My cart</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock %}

{# 网页主体内容块 #}
{% block body %}{% endblock %}
<div class="footer">
    <div class="foot_link">
        <a href="#">About us</a>
        <span>|</span>
        <a href="#">Contact us</a>
        <span>|</span>
        <a href="#">Careers</a>
        <span>|</span>
        <a href="#">Useful links</a>
    </div>
    <p>CopyRight © 2021 天天生鲜 All Rights Reserved</p>
    <p>Privacy Policy</p>
</div>
{# 网页底部html引入元素块 #}
{% block bottom %}{% endblock %}

{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock %}
</body>
</html>

templates/base_detail_list.html
{# Details and lists page #}
{% extends 'base.html' %}
{% block body %}
<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>All products</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">Home page</a></li>
				<li class="interval">|</li>
				<li><a href="">Mobile dailyfresh</a></li>
				<li class="interval">|</li>
				<li><a href="">Rewards</a></li>
			</ul>
		</div>
	</div>
{# Details and lists main block #}
{% block main_content %}{% endblock %}
{% endblock %}

templates/base_user_center.html
{# User center #}
{% extends 'base_no_cart.html' %}
{% block title %}Dailyfresh-usercenter{% endblock %}
{% block page_title %}User center{% endblock %}
{% block body %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>User center</h3>
        <ul>
            <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· Personal Info</a></li>
            <li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· Orders</a></li>
            <li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· Shipment Address</a></li>
        </ul>
    </div>
    {# User center right_content #}
    {% block right_content %}
    {% endblock %}
</div>
{% endblock %}

templates/cart.html
{% extends 'base_no_cart.html' %}
{% load static from staticfiles %}
{% block title %}Dailyfresh cart{% endblock title %}
{% block page_title %}Cart{% endblock page_title %}
{% block body %}
	<div class="total_count">All products<em>{{ total_count }}</em>items</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">Product</li>
		<li class="col02">Unit</li>
		<li class="col03">Price</li>
		<li class="col04">Quantity</li>
		<li class="col05">Subtotal</li>
		<li class="col06">Operation</li>
	</ul>
    {# traverse to show records #}
    <form method="post" action="{% url 'order:place' %}">
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>${{ sku.price }}/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}USD</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">{{ sku.amount }}USD</li>
		<li class="col08"><a href="javascript:;">Delete</a></li>
	</ul>
	{% endfor %}

	<ul class="settlements">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">Select all</li>
		<li class="col03">Total：<span>$</span><em>{{ total_price }}</em><br>Include<b>{{ total_count }}</b>items</li>
		<li class="col04"><input type="submit" value="Continue" style="width: 150px; height: 50px; background-color: #37ab40; font-size: 20px; color: #fff"></li>
	</ul>
    </form>
{% endblock body %}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
		<script>
    // 计算被选中的商品的总件数和总价格
    function update_page_info() {
        // 获取所有被选中的商品的checkbox
        // 获取所有被选中的商品所在的ul元素
        total_count = 0
        total_price = 0
        $('.cart_list_td').find(':checked').parents('ul').each(function () {
            // 获取商品的数目和小计
            count = $(this).find('.num_show').val()
            amount = $(this).children('.col07').text()
            // 累加计算商品的总件数和总价格
            count = parseInt(count)
            amount = parseFloat(amount)
            total_count += count
            total_price += amount
        })
        // 设置被选中的商品的总件数和总价格
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)
    }

    // 计算商品的小计
    function update_goods_amount(sku_ul) {
        // 获取商品的价格和数量
        var count = sku_ul.find('.num_show').val()
        var price = sku_ul.children('.col05').text()
        // 计算商品的小计
        var amount = parseInt(count)*parseFloat(price)
        // 设置商品的小计
        sku_ul.children('.col07').text(amount.toFixed(2) + "USD")
    }

    // 商品的全选和全不选
    $('.settlements').find(':checkbox').change(function () {
        // 获取全选的checkbox的选中状态
        is_checked = $(this).prop('checked')
        // 遍历商品的对应的checkbox，设置这些checkbox的选中状态和全选的checkbox保持一致
        $('.cart_list_td').find(':checkbox').each(function () {
            $(this).prop('checked', is_checked)
        })
        // 更新页面的信息
        update_page_info()
    })

    // 商品对应的checkbox状态发生改变时，设置全选checkbox的状态
    $('.cart_list_td').find(':checkbox').change(function () {
        // 获取页面上所有商品的数目
        all_len = $('.cart_list_td').length
        // 获取页面上被选中的商品的数目
        checked_len = $('.cart_list_td').find(':checked').length
        is_checked = true
        if (checked_len < all_len){
            is_checked = false
        }
        $('.settlements').find(':checkbox').prop('checked', is_checked)
        // 更新页面的信息
        update_page_info()
    })

    // 更新购物车中商品的数量
    error_update = false
    total = 0
    function update_remote_cart_info(sku_id, count) {
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 组织参数
        params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
        // 设置ajax请求为同步
        $.ajaxSettings.async = false
        // 发起ajax post请求，访问/cart/update, 传递参数:sku_id count
        // 默认发起的ajax请求都是异步的，不会等回调函数执行
        $.post('/cart/update', params, function (data) {
            if (data.res == 5){
                // 更新成功
                error_update = false
                total = data.total_count
            }
            else{
                // 更新失败
                error_update = true
                alert(data.errmsg)
            }
        })
        // 设置ajax请求为异步
        $.ajaxSettings.async = true
    }

    // 购物车商品数量的增加
    $('.add').click(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).next().attr('sku_id')
        count = $(this).next().val()

        // 组织参数
        count = parseInt(count)+1

        // 更新购物车记录
        update_remote_cart_info(sku_id, count)
        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).next().val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
    })

    // 购物车商品数量的减少
    $('.minus').click(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).prev().attr('sku_id')
        count = $(this).prev().val()

        // 校验参数
        count = parseInt(count)-1
        if (count <= 0){
            return
        }

        // 更新购物车中的记录
        update_remote_cart_info(sku_id, count)

        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).prev().val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
    })

    // 记录用户输入之前商品的数量
    pre_count = 0
    $('.num_show').focus(function () {
        pre_count = $(this).val()
    })

    // 手动输入购物车中的商品数量
    $('.num_show').blur(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).attr('sku_id')
        count = $(this).val()

        // 校验参数
        if (isNaN(count) || count.trim().length==0 || parseInt(count)<=0){
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
            return
        }

        // 更新购物车中的记录
        count = parseInt(count)
        update_remote_cart_info(sku_id, count)

        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
        else{
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
        }
    })

    // 删除购物车中的记录
    $('.cart_list_td').children('.col08').children('a').click(function () {
        // 获取对应商品的id
        sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 组织参数
        params = {'sku_id':sku_id, 'csrfmiddlewaretoken':csrf}
        // 获取商品所在的ul元素
        sku_ul = $(this).parents('ul')
        // 发起ajax post请求， 访问/cart/delete, 传递参数:sku_id
        $.post('/cart/delete', params, function (data) {
            if (data.res == 3){
                // 删除成功，异常页面上商品所在的ul元素
                sku_ul.remove()
                // 获取sku_ul中商品的选中状态
                is_checked = sku_ul.find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新页面信息
                    update_page_info()
                }
                // 重新设置页面上购物车中商品的总件数
                $('.total_count').children('em').text(data.total_count)
            }
            else{
                alert(data.errmsg)
            }
        })
    })

    </script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Dailyfresh{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">All goods</h1>
			<ul class="navlist fl">
				<li><a href="">Home page</a></li>
				<li class="interval">|</li>
				<li><a href="">Mobile dailyfresh</a></li>
				<li class="interval">|</li>
				<li><a href="">Rewards</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">See more ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">$ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}Dailyfresh product list{% endblock %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">All products</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>Fresh products</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">${{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>Default</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>Price</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>Hot</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">${{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="Add to cart"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">previous</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">next</a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_content %}
<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">User info</h3>
						<ul class="user_info_list">
							<li><span>User：</span>{{ user.username }}</li>
							{% if address %}
								<li><span>Phone：</span>{{ address.phone }}</li>
								<li><span>Address：</span>{{ address.addr }}</li>
							{% else %}
								<li><span>Phone：</span>None</li>
								<li><span>Address：</span>None</li>
							{% endif %}
						</ul>
				</div>

				<h3 class="common_title2">Recent browse</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						{% for goods in goods_li %}
						<li>
							<a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
							<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
							<div class="operate">
								<span class="prize">${{ goods.price }}</span>
								<span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
								<a href="#" class="add_goods" title="Add to cart"></a>
							</div>
						</li>
						{% empty %}
							No recent browse
						{% endfor %}
					</ul>
		</div>
		</div>
{% endblock %}